// src/components/print/AltIngredients.tsx
import AltIngredient from './AltIngredient';
import type {AltIngredientType} from "../../content/config.ts";

export default function AltIngredients(alt_ingredients: any) {
    return (
        <ul>
                {alt_ingredients.alt_ingredients.map((alt_ingredient: object, index: number) => (
                    <AltIngredient alt_ingredient={alt_ingredient} key={index}/>
                ))}
        </ul>
    );
}

// src/components/print/AltIngredients.svelte
<script lang="ts">
  import AltIngredient from './AltIngredient.svelte';
  import type { AltIngredientType } from "../../content/config.ts";
  
  export let alt_ingredients: AltIngredientType[];
</script>

<ul>
  {#each alt_ingredients as alt_ingredient}
    <AltIngredient {alt_ingredient} />
  {/each}
</ul>
