// src/components/print/Print.svelte
<script lang="ts">
  import { eaters, allergies } from "../stores/eatersStore.ts";
  import type { AllergyType, RecipeIngredientType } from "../../content/config.ts";
  import Ingredients from "./Ingredients.svelte";
  import { onMount } from "svelte";
  
  export let title: string;
  export let description: string;
  export let date: string;
  export let tags: string[];
  export let ingredients: RecipeIngredientType[];
  
  $: $eaters;
  $: $allergies;
  
  $: recipe_allergies = ingredients
    .map((ingredient: RecipeIngredientType) => ingredient.ingredient.allergies)
    .flat()
    .filter(Boolean);
  
  onMount(() => {
    window.print();
  });
</script>

<h1 class="text-center font-bold text-3xl">
  {title}
</h1>

<div class="grid grid-cols-2">
  <div>
    <h2 class="font-bold text-xl pt-4">Ingredienten</h2>
    <Ingredients {ingredients} />
  </div>

  <div>
    {#if recipe_allergies.length > 0}
      <h2 class="font-bold text-xl pt-4">Allergenen</h2>
      <ul>
        {#each recipe_allergies as allergy}
          <span>{allergy.name}, </span>
        {/each}
      </ul>
    {/if}

    <h2 class="font-bold text-xl pt-4">Eeters</h2>
    <span class="font-medium">Totaal: {$eaters}</span><br/>
    {#if Object.keys($allergies).length > 0}
      Waarvan met allergie:
      <ul>
        {#each Object.entries($allergies) as [key, value]}
          {#if recipe_allergies.some((allergy) => allergy.name === key)}
            <li>
              {key}: {value}
            </li>
          {/if}
        {/each}
      </ul>
    {/if}
  </div>
</div>

<h2 class="font-bold text-xl pt-4">Bereiding</h2>
<div class="prose max-w-full text-black prose-ul:text-black leading-5">
  <slot></slot>
</div>

// src/components/print/Print.tsx
// src/components/print/Print.tsx
import React from 'react';
import {eaters, allergies} from "../stores/eatersStore.ts";
import {useStore} from '@nanostores/react';
import type {AllergyType, RecipeIngredientType} from "../../content/config.ts";
import Ingredients from "./Ingredients.tsx";
import {useEffect} from "react";

interface PrintProps {
    title: string;
    description: string;
    date: string;
    tags: string[];
    ingredients: RecipeIngredientType[];
    children: React.ReactNode;
}

const Print = (props: PrintProps) => {
    const $eaters = useStore(eaters);
    const $allergies = useStore(allergies);

    let recipe_allergies = props.ingredients
        .map((ingredient: RecipeIngredientType) => ingredient.ingredient.allergies)
        .flat()
        .filter(Boolean);

    useEffect(() => {
        window.print();
    }, [])

    return (
        <>
            <h1 className="text-center font-bold text-3xl">
                {props.title}
            </h1>

            <div className={'grid grid-cols-2'}>
                <div>
                    <h2 className="font-bold text-xl pt-4">Ingredienten</h2>
                    <Ingredients ingredients={props.ingredients}></Ingredients>
                </div>

                <div>
                    {recipe_allergies.length > 0 &&
                        <>
                            <h2 className="font-bold text-xl pt-4">Allergenen</h2>
                            <ul>
                                {recipe_allergies.map((allergy: AllergyType) => (
                                    <span>{allergy.name}, </span>
                                ))}
                            </ul>
                        </>
                    }

                    <h2 className="font-bold text-xl pt-4">Eeters</h2>
                    <span className={'font-medium'}>Totaal: {$eaters}</span><br/>
                    {$allergies.length > 0 && <>
                        Waarvan met allergie:
                        <ul>
                            {Object.entries($allergies).map(([key, value]) =>
                                    recipe_allergies.some((allergy: any) => allergy.name === key) && (
                                        <li key={key}>
                                            {key}: {value as React.ReactNode}
                                        </li>
                                    )
                            )}
                        </ul>
                    </>}
                </div>
            </div>

            <h2 className="font-bold text-xl pt-4">Bereiding</h2>
            <div className="prose max-w-full text-black prose-ul:text-black leading-5">
                {props.children}
            </div>

        </>
    );
}

export default Print;
