// src/lib/components/ingredients/AltIngredients.svelte
<script lang="ts">
  import AltIngredient from './AltIngredient.svelte';
  import type { AlternativeOutSchema, AllergyOutSchema } from "$lib/client/types.gen";

  interface Props {
    alt_ingredient: AlternativeOutSchema;
    allergies?: AllergyOutSchema[];
  }

  let { alt_ingredient, allergies }: Props = $props();
</script>

<div class="bg-slate-400 rounded shadow p-1">
  <table class="w-full">
    <thead>
      <tr class="font-medium">
        <td>Alternatief ingredient</td>
        <td>Voor allergie</td>
        <td>Hoeveelheid p.p.</td>
        <td>Hoeveelheid totaal</td>
      </tr>
    </thead>
    <tbody>
      <AltIngredient {alt_ingredient} {allergies} />
    </tbody>
  </table>
</div>

// src/components/ingredients/AltIngredients.tsx
import AltIngredient from './AltIngredient';

export default function AltIngredients(alt_ingredients) {
    return (
        <table className={'bg-slate-400 w-full rounded shadow'}>
            <thead>
                <tr className={'font-medium'}>
                    <td>Ingredient</td>
                    <td>Voor allergie</td>
                    <td>Hoeveelheid p.p.</td>
                    <td>Hoeveelheid totaal</td>
                </tr>
            </thead>
            <tbody>
                {alt_ingredients.alt_ingredients.map((alt_ingredient, index) => (
                    <AltIngredient alt_ingredient={alt_ingredient} key={index} />
                ))}
            </tbody>
        </table>
    );
}
