// src/lib/components/eaters/Eaters.svelte
<script lang="ts">
  import EaterInput from "./EaterInput.svelte";
  import { eaters } from '../stores/eatersStore.svelte';

  let allergies = $props();

  function handleInputChange(event) {
    const newValue = parseInt(event.target.value, 10);
    if (!isNaN(newValue)) {
      eaters.set(newValue);
    }
  }
</script>

<div class="bg-slate-200 rounded p-2 mb-4">
  <div class="flex flex-col gap-4">
    <div class="flex gap-4">
      <label class="text-nowrap">Aantal eters totaal:</label>
      <input class="w-full rounded px-1 py-0.5" value={eaters} on:input={handleInputChange}/>
    </div>
    <div class="bg-slate-300 rounded p-2">
      <div class="mb-2">
        <h6 class="text-sm">Waarvan met een .... allergie:</h6>
      </div>

      <div class="flex flex-col gap-2">
        {#each allergies as allergy}
          <EaterInput {allergy} />
        {/each}
      </div>
    </div>
  </div>
</div>

// src/components/eaters/Eaters.tsx
import EaterInput from "./EaterInput.tsx";
import {useStore} from "@nanostores/react";
import {eaters, updateAllergies} from '../stores/eatersStore';
import type {AllergyType} from "../../content/config.ts";

export default function Eaters(allergies: any){
    const $eaters = useStore(eaters);

    const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const newValue = parseInt(event.target.value, 10);
        if (!isNaN(newValue)) {
            eaters.set(newValue);
        }
    };

    return (
        <div className={'bg-slate-200 rounded p-2 mb-4'}>
            <div className={'flex flex-col gap-4'}>
                <div className={'flex gap-4'}>
                    <label className={'text-nowrap'}>Aantal eters:</label>
                    <input className={"w-full rounded px-1 py-0.5"} value={$eaters} onChange={handleInputChange}/>
                </div>

                {allergies.allergies.map((allergy: AllergyType) => (
                    <EaterInput allergy={allergy} key={allergy.name}/>
                ))}
            </div>
        </div>
    );
}
