// src/components/ingredients/Ingredients.svelte
<script lang="ts">
  import Ingredient from "./Ingredient.svelte";
  import type { RecipeIngredientType } from '../../content/config.ts';
  
  export let ingredients: RecipeIngredientType[];
</script>

<div class="bg-slate-200 rounded mb-4 overflow-x-auto">
  <table class="w-full text-nowrap whitespace-nowrap">
    <thead class="text-left">
      <tr class="border-b-2 border-slate-400">
        <th class="p-2">Ingredient</th>
        <th class="p-2">Allergieën</th>
        <th class="p-2">Hoeveelheid p.p.</th>
        <th class="p-2">Totaal</th>
      </tr>
    </thead>
    <tbody>
      {#each ingredients as ingredient, index}
        <Ingredient {ingredient} />
      {/each}
    </tbody>
  </table>
</div>

// src/components/Ingredients.tsx
import Ingredient from "./Ingredient";
import type {RecipeIngredientType} from '../content/config.ts';

export default function Ingredients({ingredients}: {ingredients: RecipeIngredientType[]}) {
    return (
        <div className={"bg-slate-200 rounded mb-4 p-2"}>
            <table className={'w-full'}>
                <thead className={'text-left'}>
                <tr>
                    <th>Ingredient</th>
                    <th>Allergieën</th>
                    <th>Hoeveelheid p.p.</th>
                    <th>Totaal</th>
                </tr>
                </thead>
                <tbody>
                {ingredients.map((ingredient: any, index: number) => (
                    <Ingredient ingredient={ingredient} key={index}/>
                ))}
                </tbody>
            </table>
        </div>
    );
}
