// src/lib/components/search/Search.svelte
<script lang="ts">
    import SearchResults from "./SearchResults.svelte";
    import {type RecipeListOutSchema, recipesApiGetRecipes} from "$lib/client";

    let recipe_count: number = $props();

    let filters = [];
    let query = '';
    let timeoutId: any = null;
    let searchInput: HTMLInputElement;
    let results: Array<RecipeListOutSchema> | undefined = $state([])


    async function search(text: string) {
        if (text.length < 2) {
            results = [];
            return;
        }

        try {
            const {data} = await recipesApiGetRecipes({ query: { name: text } });
            results = data;
        } catch (err) {
            console.error('search error', err);
        }

        // Clear the timeout if it's already set.
        if (timeoutId) {
            clearTimeout(timeoutId);
        }

        // Set the timeout to execute the umami.trackEvent after 2 seconds.
        timeoutId = setTimeout(() => {
            try {
                // @ts-ignore
                umami.trackEvent('search', {
                    query: text,
                    results: results.length
                });
            } catch (e) {
            }
        }, 2000);
    }

    function handleInputChange(e) {
        query = e.target.value;
        search(query);
    }
</script>

<div>
    <input class="w-full bg-slate-300 rounded px-2 py-2 placeholder:font-medium placeholder:text-slate-500"
           bind:value={query}
           bind:this={searchInput}
           placeholder={`Zoek door alle recepten`}
           on:input={handleInputChange}
           autocapitalize="off"
           autocomplete="off"
           autocorrect="off"
           spellcheck="false">
    <SearchResults bind:results={results}/>
    <!--  <SearchFilters {filters}/>-->
</div>

// src/components/search/Search.tsx
import {useState, useEffect, useRef} from 'react';
import SearchResults from "./SearchResults";

const Search = (props) => {
    const [pagefind, setPagefind] = useState(null);
    const [query, setQuery] = useState('');
    const [resultsOBJ, setResultsOBJ] = useState(null);
    let timeoutId: any = null;
    const searchInput = useRef(null);

    const recipe_count = props.recipe_count;

    const search = async (text: string) => {
        if (pagefind) {
            let results = await pagefind.debouncedSearch(text);
            if(results){
                setResultsOBJ(results.results);
            }

            // Clear the timeout if it's already set.
            if (timeoutId) {
                clearTimeout(timeoutId);
            }

            // Set the timeout to execute the umami.trackEvent after 3 seconds.
            timeoutId = setTimeout(() => {
                try {
                    umami.trackEvent('search', {
                        query: text,
                        results: results.results.length
                    });
                } catch (e) {
                }
            }, 2000);
        }
    }

    useEffect(() => {
        const fetchPagefind = async () => {
            // @ts-ignore
            const pagefindModule = await import("/pagefind/pagefind.js");
            setPagefind(pagefindModule);
            pagefindModule.init();
        }
        fetchPagefind();
    }, []);

    return (
        <div>
            <input className="w-full bg-slate-300 rounded px-2 py-2 placeholder:font-medium placeholder:text-slate-500" value={query} ref={searchInput}
                   placeholder={`Zoek door alle ${recipe_count} recepten`}
                   onChange={(e) => {
                       setQuery(e.target.value);
                       search(e.target.value);
                   }}
                   autoCapitalize="off" autoComplete="off" autoCorrect="off" spellCheck="false">
            </input>
            <SearchResults results={resultsOBJ} searchInput={query}/>
        </div>
    );
}

export default Search;
