// src/components/search/SearchResults.tsx
import {useEffect, useState} from 'react';

export default function SearchResults({results, searchInput}: {results: any, searchInput: string}) {
    const [data, setData] = useState([]);

    useEffect(() => {
        const fetchData = async () => {
            if (results) {
                const newData = await Promise.all(results.map(result => result.data()));
                setData(newData);
            }
        }
        fetchData();
    }, [results]);


    return (
        <div className="flex gap-2 flex-col pt-2">
            {data.length > 0 ? data.map((result_data, index) => (
                <a href={result_data.url} className={'bg-slate-300 p-2 rounded shadow'} key={index}>
                    <h3 className={'text-xl font-bold'}>{result_data.meta.title}</h3>
                    <div className={'flex flex-wrap gap-1 mt-1.5'}>
                        <div className={'px-1 py-0.5 text-sm'}>Ingredienten: </div>
                        {result_data.filters.ingredient.map((filter, filterIndex) => (
                            <span key={filterIndex}
                                  className={'bg-slate-400 px-1 py-0.5 rounded text-white text-sm'}>{filter}</span>
                        ))}
                    </div>
                </a>
            )) : (searchInput.length > 0) ? <div className={'bg-slate-300 p-2 rounded shadow'}>Geen recepten gevonden</div> : null}
        </div>
    );
}

// src/lib/components/public/search/SearchResults.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  const {results = $bindable()} = $props();
</script>

<div class="flex gap-2 flex-col pt-2">
  {#if results.length > 0}
    {#each results as result, index}
      <a href={`recepten/${result.name}-${result.sqid}`} class="bg-slate-300 p-2 rounded shadow">
        <h3 class="text-xl font-bold">{result.name}</h3>
        <div class="flex flex-wrap gap-1 mt-1.5">
          <div class="px-1 py-0.5 text-sm">Ingredienten: </div>
          <!--{#each result.filters.ingredient as filter, filterIndex}-->
          <!--  <span class="bg-slate-400 px-1 py-0.5 rounded text-white text-sm">{filter}</span>-->
          <!--{/each}-->
        </div>
      </a>
    {/each}
  {:else if results.length > 0}
    <div class="bg-slate-300 p-2 rounded shadow">Geen recepten gevonden</div>
  {/if}
</div>
